# Generated by Django 5.0.1 on 2026-06-23 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255, unique=True)),
                ("derivation_index", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_addresses",
                        to="wallet.coin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_hash", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=36)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("CREDITED", "Credited"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("block_number", models.PositiveBigIntegerField(blank=True, null=True)),
                ("confirmations", models.PositiveIntegerField(default=0)),
                ("credited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to="wallet.coin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="core_deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deposit_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deposits",
                        to="core.depositaddress",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlatformWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "balance",
                    models.DecimalField(decimal_places=18, default=0, max_digits=36),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_wallet",
                        to="wallet.coin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Wallet",
                "verbose_name_plural": "Platform Wallets",
            },
        ),
        migrations.AddIndex(
            model_name="depositaddress",
            index=models.Index(
                fields=["address"], name="core_deposi_address_6bbc22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depositaddress",
            index=models.Index(fields=["coin"], name="core_deposi_coin_id_a0a8fe_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="depositaddress",
            unique_together={("user", "coin")},
        ),
        migrations.AddIndex(
            model_name="deposit",
            index=models.Index(fields=["status"], name="core_deposi_status_c037bb_idx"),
        ),
        migrations.AddIndex(
            model_name="deposit",
            index=models.Index(
                fields=["user", "coin"], name="core_deposi_user_id_cdec4d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deposit",
            unique_together={("coin", "tx_hash")},
        ),
    ]
