"""
Django settings for malov project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os 
import environ
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),  # default DEBUG to False if not set
)
environ.Env.read_env(BASE_DIR / ".env")  # load your .env file


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%(h)n9egb%%*smaxwt3yf$&%dht25-%fel=clu20ig6wztvg_k"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

     # third party
    'rest_framework',
    'drf_spectacular',
    "corsheaders",


    # local apps
    'accounts.apps.AccountsConfig', 
    'core',
    'chat',
    'deposit',
    'kyc',
    'wallet',
    'p2p',
    'withdraw',

]

SPECTACULAR_SETTINGS = {
    "TITLE": "Malov API",
    "DESCRIPTION": "Wallet + P2P + Chat + KYC System",
    "VERSION": "1.0.0",

    # 🔥 IMPORTANT FOR CLEAN SCHEMA
    "COMPONENT_SPLIT_REQUEST": True,

    # 🔥 Better schema structure
    "SCHEMA_PATH_PREFIX": "/api/",

    # 🔥 cleaner enums
    "ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE": True,

    # 🔥 prevents schema duplication noise
    "SERVE_INCLUDE_SCHEMA": False,
}


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}



SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", 
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "malov.urls"


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://marovgroup.com",
    "https://www.marovgroup.com",
    "http://localhost:4001",
    "http://127.0.0.1:4001",
]

CORS_ALLOW_CREDENTIALS = True



CORS_ALLOW_HEADERS = list(default_headers) + [
    "authorization",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "malov.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.User"

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "sync-all-platform-wallets": {
        "task": "core.tasks.run_sync_all_platform_wallets",
        "schedule": 60.0,
    },
    "poll-tron-deposits": {
        "task": "core.tasks.poll_tron_deposits",
        "schedule": 15.0,
    },
}

# RPC
ETH_RPC_URL     = env("ETH_RPC_URL",     default="")
BSC_RPC_URL     = env("BSC_RPC_URL",     default="")
POLYGON_RPC_URL = env("POLYGON_RPC_URL", default="")

# Alchemy
ALCHEMY_AUTH_TOKEN      = env("ALCHEMY_AUTH_TOKEN",      default="")
ALCHEMY_SIGNING_KEY     = env("ALCHEMY_SIGNING_KEY",     default="")
ALCHEMY_WEBHOOK_ID_ETH  = env("ALCHEMY_WEBHOOK_ID_ETH",  default="")
ALCHEMY_WEBHOOK_ID_BNB  = env("ALCHEMY_WEBHOOK_ID_BNB",  default="")
ALCHEMY_WEBHOOK_ID_POL  = env("ALCHEMY_WEBHOOK_ID_POL",  default="")

# BlockCypher
BLOCKCYPHER_API_KEY = env("BLOCKCYPHER_API_KEY", default="")

# TronGrid
TRONGRID_API_KEY = env("TRONGRID_API_KEY", default="")

# xpubs (public — safe on server)
BTC_ACCOUNT_XPUB  = env("BTC_ACCOUNT_XPUB",  default="")
EVM_ACCOUNT_XPUB  = env("EVM_ACCOUNT_XPUB",  default="")
TRON_ACCOUNT_XPUB = env("TRON_ACCOUNT_XPUB", default="")

# xprvs (private — signing keys, treat like passwords)
BTC_ACCOUNT_XPRV  = env("BTC_ACCOUNT_XPRV",  default="")
EVM_ACCOUNT_XPRV  = env("EVM_ACCOUNT_XPRV",  default="")
TRON_ACCOUNT_XPRV = env("TRON_ACCOUNT_XPRV", default="")


# xprvs (private — signing only, treat like passwords)
BTC_ACCOUNT_XPRV  = env("BTC_ACCOUNT_XPRV",  default="")
EVM_ACCOUNT_XPRV  = env("EVM_ACCOUNT_XPRV",  default="")
TRON_ACCOUNT_XPRV = env("TRON_ACCOUNT_XPRV", default="")

# Central wallet addresses (from central_wallets.PUBLIC.json)
CENTRAL_BTC_ADDRESS  = env("CENTRAL_BTC_ADDRESS",  default="")
CENTRAL_EVM_ADDRESS  = env("CENTRAL_EVM_ADDRESS",  default="")
CENTRAL_TRON_ADDRESS = env("CENTRAL_TRON_ADDRESS", default="")

# Approval HMAC secret (shared with signing service)
APPROVAL_HMAC_SECRET = env("APPROVAL_HMAC_SECRET", default="")

# Signing service internal URL
SIGNING_SERVICE_URL = env("SIGNING_SERVICE_URL", default="http://signer:8001")

# BlockCypher webhook token
BLOCKCYPHER_WEBHOOK_TOKEN = env("BLOCKCYPHER_WEBHOOK_TOKEN", default="")
# Public base URL
PUBLIC_BASE_URL = env("PUBLIC_BASE_URL", default="http://localhost:8000")