# Generated by Django 5.0.1 on 2026-06-26 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("p2p", "0001_initial"),
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyoffer",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="selloffer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="selloffer",
            name="number",
        ),
        migrations.RemoveField(
            model_name="selloffer",
            name="payment_method",
        ),
        migrations.AlterField(
            model_name="buyoffer",
            name="coin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buy_offers",
                to="wallet.coin",
            ),
        ),
        migrations.AlterField(
            model_name="buyoffer",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buy_offers",
                to="p2p.currency",
            ),
        ),
        migrations.AlterField(
            model_name="buyoffer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buy_offers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="selloffer",
            name="coin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sell_offers",
                to="wallet.coin",
            ),
        ),
        migrations.AlterField(
            model_name="selloffer",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sell_offers",
                to="p2p.currency",
            ),
        ),
        migrations.AlterField(
            model_name="selloffer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sell_offers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MyPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_payment_methods",
                        to="p2p.paymentmethod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "payment_method", "number")},
            },
        ),
        migrations.CreateModel(
            name="BuyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=6, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buy_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="p2p.buyoffer",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_orders_as_buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_orders_as_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client_payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buy_orders",
                        to="p2p.mypaymentmethod",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="buyoffer",
            name="payment_methods",
            field=models.ManyToManyField(
                related_name="buy_offers", to="p2p.mypaymentmethod"
            ),
        ),
        migrations.AddField(
            model_name="selloffer",
            name="payment_methods",
            field=models.ManyToManyField(
                related_name="sell_offers", to="p2p.mypaymentmethod"
            ),
        ),
        migrations.CreateModel(
            name="SellOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=6, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_orders_as_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client_payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sell_orders",
                        to="p2p.mypaymentmethod",
                    ),
                ),
                (
                    "sell_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="p2p.selloffer",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_orders_as_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
