# Generated by Django 5.0.1 on 2026-06-26 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_sweeptask_coin_userwallet_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalrequest",
            name="level",
            field=models.CharField(
                choices=[("USER", "User"), ("SERVER", "Server"), ("HSM", "HSM")],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="sweeptask",
            name="amount_raw",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="userwallet",
            name="network",
            field=models.CharField(
                choices=[
                    ("BTC", "Bitcoin"),
                    ("ETH", "Ethereum"),
                    ("BNB", "BNB Smart Chain"),
                    ("POL", "Polygon"),
                    ("TRON", "TRON"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userwallet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_wallets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
