# Generated by Django 5.0.1 on 2026-06-23 10:52

import django.db.models.deletion
import withdraw.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
        ("withdraw", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="withdraw",
            name="failure_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdraw",
            name="reference",
            field=models.CharField(
                default=withdraw.models.generate_reference, max_length=64, unique=True
            ),
        ),
        migrations.AddField(
            model_name="withdraw",
            name="tx_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="withdraw",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="amount",
            field=models.DecimalField(decimal_places=18, max_digits=36),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdrawals_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdrawals_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="status",
            field=models.CharField(
                choices=[
                    ("INTERNAL", "Internal"),
                    ("PENDING", "Pending"),
                    ("BROADCASTING", "Broadcasting"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="INTERNAL",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="withdraw",
            index=models.Index(fields=["status"], name="withdraw_wi_status_0fa8fd_idx"),
        ),
        migrations.AddIndex(
            model_name="withdraw",
            index=models.Index(
                fields=["sender"], name="withdraw_wi_sender__ae734f_idx"
            ),
        ),
    ]
