# Generated by Django 5.0.1 on 2026-06-21 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrivingLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("place_of_birth", models.CharField(max_length=255)),
                ("residence_address", models.TextField()),
                ("driving_licence_number", models.CharField(max_length=100)),
                ("date_of_issuance", models.DateField()),
                ("date_of_expiry", models.DateField()),
                ("issuing_at", models.CharField(max_length=255)),
                ("issuing_authority", models.CharField(max_length=255)),
                ("card_number", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="kyc/driving_licenses/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driving_licenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KYC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kycs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NationalID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("place_of_birth", models.CharField(max_length=255)),
                ("mother", models.CharField(max_length=255)),
                ("father", models.CharField(max_length=255)),
                ("occupation", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=50)),
                ("marriage_status", models.CharField(max_length=100)),
                ("nmifp", models.CharField(max_length=100)),
                ("issuing_at", models.CharField(max_length=255)),
                ("issuing_authority", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="national_ids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("passport_number", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=255)),
                ("nationality", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("personal_identity_number", models.CharField(max_length=100)),
                ("sex", models.CharField(max_length=20)),
                ("place_of_birth", models.CharField(max_length=255)),
                ("date_of_issuance", models.DateField()),
                ("date_of_expiry", models.DateField()),
                ("issuing_authority", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="kyc/passports/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
